version: 2

models:
    - name: weather
      description: "Iowa weather info"
      columns:
        - name: date
          description: "The primary key for this table"
          tests:
              - unique
              - not_null
