version: 2

models:
    - name: triple_sec_weather
      description: "triple sec sales per day with weather info"
      columns:
        - name: date
          description: "The primary key for this table"
          tests:
              - unique
              - not_null
